CREATE DATABASE IF NOT EXISTS movies_collection;

USE movies_collection;

CREATE TABLE movies (
	id BIGINT NOT NULL AUTO_INCREMENT,
	title VARCHAR(40) UNIQUE NOT NULL, 
	release_date DATE NOT NULL,
	movie_box_office_revenue BIGINT,
	plot_summary text NOT NULL,
	feature_length BIGINT,
	PRIMARY KEY(id)
);

CREATE TABLE countries (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(40) UNIQUE NOT NULL
);

CREATE TABLE movies_countries(
	movie_id BIGINT NOT NULL,
	country_id BIGINT NOT NULL,
	FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (country_id) REFERENCES countries (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY (movie_id, country_id)
);

CREATE TABLE genres (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(40) NOT NULL
);


CREATE TABLE movies_genres(
	movie_id BIGINT NOT NULL,
	genre_id BIGINT NOT NULL,
	FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY (movie_id, genre_id)
);

CREATE TABLE languages (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(40) UNIQUE NOT NULL
);


CREATE TABLE movies_languages(
	movie_id BIGINT NOT NULL,
	language_id BIGINT NOT NULL,
	FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (language_id) REFERENCES languages (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY (movie_id, language_id)
);
